apiVersion: 1

contactPoints:
  - orgId: 1
    name: incident-response
    receivers:
      - uid: incident-response-webhook
        type: webhook
        settings:
          url: http://host.docker.internal:8001/alerts
          httpMethod: POST

policies:
  - orgId: 1
    receiver: incident-response
    group_by: [alertname, http_route]
    group_wait: 0s
    group_interval: 1m
    repeat_interval: 4h
